language: php

php:
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install puppeteer
  - npm install pixelmatch
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - export DISPLAY=:99.0
  - Xvfb -ac :0 -screen 0 1920x1080x16 &
  - ./vendor/laravel/dusk/bin/chromedriver-linux &

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
